### PR TITLE
Minimal path change needed for galaxy PR 16795

### PR DESCRIPTION
**Pull request by sveinugu**
Also requires new version 0.0.6 of gx-it-proxy (galaxyproject/gx-it-proxy#17).

Should result in a new release 1.0.4 after merge (as required by galaxyproject/galaxy#16795). @natefoo?

Replaces https://github.com/elixir-oslo/gravity/pull/2 which was within my own repo and just stupid! 😅

### CODE REVIEW

**Comment by sveinugu** [comment]
Status: https://github.com/galaxyproject/gx-it-proxy/pull/17 has been merged, but awaiting version change, which I believe depends on https://github.com/galaxyproject/gx-it-proxy/issues/16#issuecomment-1778707676.

**Comment by sveinugu** [comment]
Ready for review and merge. https://github.com/galaxyproject/gx-it-proxy/pull/17 is merged and v0.0.6 of gx-it-proxy released. @natefoo ?

**Comment by sveinugu** [comment]
Ping @natefoo ?

**Review by natefoo — APPROVED** [review]
Sorry for the delay, thanks for taking care of all the pieces so thoroughly!

**Pull request merged**
