### PR TITLE
Add support for yaml job config

### PR DESCRIPTION
**Pull request by mvdbeek**
(as an external file, should also support embedding directly in galaxy config)

### CODE REVIEW

**Comment by natefoo** [comment]
Since you're parsing the job conf now, should we pull out the tags for `--attach-to-pool`?

**Comment by mvdbeek** [comment]
We could do that, yeah. But this could be redundant/conflicting with specifying the process config like this: https://github.com/galaxyproject/gravity/blob/8dbedebad6a7b8a792608c2f86834248f3683c29/tests/test_process_manager.py#L28

Should we drop the pools argument from the gravity config and just specify how many processes to start in the gravity section ?

**Comment by natefoo** [comment]
That was always sort of a stopgap since we weren't reading the job config. Not great to be defining things in two places.

**Comment by mvdbeek** [comment]
I agree, but I think it'd also be weird to put the number of processes into the job config ? I guess we'll have to keep splitting this between the gravity section (for number of processes) and the job conf.

**Pull request merged**
