### PR TITLE
Gunicorn/fastAPI support, click support, tests

### PR DESCRIPTION
**Pull request by mvdbeek**
Making some progress here, I think there's a realistic chance we could ship Galaxy with this.
There's still a lot that doesn't work, but we also still have some time until the 22.01 release.

### CODE REVIEW

**Comment by natefoo** [comment]
I am pretty sure the instance name was to support managing multiple instances from a single gravity deployment. You could set the instance name, but if you didn't then a UUID is generated and used instead.

I don't think it's intentional that the instance name is changing. I don't think we need support for multiple instances, if this is intended to be run from Galaxy's venv (although I could imagine installing gravity system-wide, in which case I guess multi-instance support could still be useful).

**Comment by natefoo** [comment]
I now recall what the point of the `cli_instance_config` branch was, as well... it's to move the configuration of multiple instances out of the galaxy config file(s) themselves and into the Gravity config. You tell Gravity to manage an instance with a certain name at a certain path, and it stores that in its own config.

**Comment by natefoo** [comment]
I suppose the entire multi-instance concept is de-facto incompatible with the removal of venv handling and the installation of gravity in the galaxy venv, since additional instances are all going to use the venv that gravity is installed in. In this case, we need to isolate the gravity configs by instance?

**Comment by natefoo** [comment]
@mvdbeek still a few things to do but rather than continue to iterate on this PR how about we merge and do additional stuff in new PRs?

**Comment by mvdbeek** [comment]
:shipit:

**Comment by natefoo** [comment]
I see you gave it a very thorough review. :rofl:

**Comment by mvdbeek** [comment]
It comes with tests, no review required 🤣

**Comment by natefoo** [comment]
I finally looked at the tests and discovered that the coverage is... well, some lines of code do get executed, so it's not nothing.

**Pull request merged**
